// <auto-generated />
namespace EveScanner
{
    partial class FitPicker
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.menuStrip1 = new System.Windows.Forms.MenuStrip();
            this.xISTABToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.xReinforcedBulkheadsToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.xExpandedCargoholdToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.xATypeAdaptiveNanoPlatingToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.button1 = new System.Windows.Forms.Button();
            this.label1 = new System.Windows.Forms.Label();
            this.button4 = new System.Windows.Forms.Button();
            this.button7 = new System.Windows.Forms.Button();
            this.label2 = new System.Windows.Forms.Label();
            this.label3 = new System.Windows.Forms.Label();
            this.button2 = new System.Windows.Forms.Button();
            this.button3 = new System.Windows.Forms.Button();
            this.button5 = new System.Windows.Forms.Button();
            this.button6 = new System.Windows.Forms.Button();
            this.button8 = new System.Windows.Forms.Button();
            this.button9 = new System.Windows.Forms.Button();
            this.okButton = new System.Windows.Forms.Button();
            this.cancelButton = new System.Windows.Forms.Button();
            this.slot1Text = new System.Windows.Forms.TextBox();
            this.slot2Text = new System.Windows.Forms.TextBox();
            this.slot3Text = new System.Windows.Forms.TextBox();
            this.menuStrip1.SuspendLayout();
            this.SuspendLayout();
            // 
            // menuStrip1
            // 
            this.menuStrip1.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.xExpandedCargoholdToolStripMenuItem,
            this.xISTABToolStripMenuItem,
            this.xATypeAdaptiveNanoPlatingToolStripMenuItem,
            this.xReinforcedBulkheadsToolStripMenuItem});
            this.menuStrip1.Location = new System.Drawing.Point(0, 0);
            this.menuStrip1.Name = "menuStrip1";
            this.menuStrip1.Size = new System.Drawing.Size(632, 24);
            this.menuStrip1.TabIndex = 0;
            this.menuStrip1.Text = "menuStrip1";
            // 
            // xISTABToolStripMenuItem
            // 
            this.xISTABToolStripMenuItem.Name = "xISTABToolStripMenuItem";
            this.xISTABToolStripMenuItem.Size = new System.Drawing.Size(124, 20);
            this.xISTABToolStripMenuItem.Text = "3x Inertial Stabilizers";
            this.xISTABToolStripMenuItem.Click += new System.EventHandler(this.MultiSelectMenu_Click);
            // 
            // xReinforcedBulkheadsToolStripMenuItem
            // 
            this.xReinforcedBulkheadsToolStripMenuItem.Alignment = System.Windows.Forms.ToolStripItemAlignment.Right;
            this.xReinforcedBulkheadsToolStripMenuItem.Name = "xReinforcedBulkheadsToolStripMenuItem";
            this.xReinforcedBulkheadsToolStripMenuItem.Size = new System.Drawing.Size(147, 20);
            this.xReinforcedBulkheadsToolStripMenuItem.Text = "3x Reinforced Bulkheads";
            this.xReinforcedBulkheadsToolStripMenuItem.Click += new System.EventHandler(this.MultiSelectMenu_Click);
            // 
            // xExpandedCargoholdToolStripMenuItem
            // 
            this.xExpandedCargoholdToolStripMenuItem.Name = "xExpandedCargoholdToolStripMenuItem";
            this.xExpandedCargoholdToolStripMenuItem.Size = new System.Drawing.Size(143, 20);
            this.xExpandedCargoholdToolStripMenuItem.Text = "3x Expanded Cargohold";
            this.xExpandedCargoholdToolStripMenuItem.Click += new System.EventHandler(this.MultiSelectMenu_Click);
            // 
            // xATypeAdaptiveNanoPlatingToolStripMenuItem
            // 
            this.xATypeAdaptiveNanoPlatingToolStripMenuItem.Alignment = System.Windows.Forms.ToolStripItemAlignment.Right;
            this.xATypeAdaptiveNanoPlatingToolStripMenuItem.Name = "xATypeAdaptiveNanoPlatingToolStripMenuItem";
            this.xATypeAdaptiveNanoPlatingToolStripMenuItem.Size = new System.Drawing.Size(194, 20);
            this.xATypeAdaptiveNanoPlatingToolStripMenuItem.Text = "3x A-Type Adaptive Nano Plating";
            this.xATypeAdaptiveNanoPlatingToolStripMenuItem.Click += new System.EventHandler(this.MultiSelectMenu_Click);
            // 
            // button1
            // 
            this.button1.Location = new System.Drawing.Point(12, 48);
            this.button1.Name = "button1";
            this.button1.Size = new System.Drawing.Size(199, 23);
            this.button1.TabIndex = 1;
            this.button1.Text = "Expanded Cargohold";
            this.button1.UseVisualStyleBackColor = true;
            this.button1.Click += new System.EventHandler(this.Slot1_Click);
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.Location = new System.Drawing.Point(93, 32);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(34, 13);
            this.label1.TabIndex = 4;
            this.label1.Text = "Slot 1";
            // 
            // button4
            // 
            this.button4.Location = new System.Drawing.Point(12, 77);
            this.button4.Name = "button4";
            this.button4.Size = new System.Drawing.Size(199, 23);
            this.button4.TabIndex = 5;
            this.button4.Text = "Inertial Stabilizers";
            this.button4.UseVisualStyleBackColor = true;
            this.button4.Click += new System.EventHandler(this.Slot1_Click);
            // 
            // button7
            // 
            this.button7.Location = new System.Drawing.Point(12, 106);
            this.button7.Name = "button7";
            this.button7.Size = new System.Drawing.Size(199, 23);
            this.button7.TabIndex = 8;
            this.button7.Text = "Reinforced Bulkheads";
            this.button7.UseVisualStyleBackColor = true;
            this.button7.Click += new System.EventHandler(this.Slot1_Click);
            // 
            // label2
            // 
            this.label2.AutoSize = true;
            this.label2.Location = new System.Drawing.Point(298, 32);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(34, 13);
            this.label2.TabIndex = 11;
            this.label2.Text = "Slot 2";
            // 
            // label3
            // 
            this.label3.AutoSize = true;
            this.label3.Location = new System.Drawing.Point(504, 32);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(34, 13);
            this.label3.TabIndex = 12;
            this.label3.Text = "Slot 3";
            // 
            // button2
            // 
            this.button2.Location = new System.Drawing.Point(217, 48);
            this.button2.Name = "button2";
            this.button2.Size = new System.Drawing.Size(199, 23);
            this.button2.TabIndex = 13;
            this.button2.Text = "Expanded Cargohold";
            this.button2.UseVisualStyleBackColor = true;
            this.button2.Click += new System.EventHandler(this.Slot2_Click);
            // 
            // button3
            // 
            this.button3.Location = new System.Drawing.Point(422, 48);
            this.button3.Name = "button3";
            this.button3.Size = new System.Drawing.Size(199, 23);
            this.button3.TabIndex = 14;
            this.button3.Text = "Expanded Cargohold";
            this.button3.UseVisualStyleBackColor = true;
            this.button3.Click += new System.EventHandler(this.Slot3_Click);
            // 
            // button5
            // 
            this.button5.Location = new System.Drawing.Point(217, 77);
            this.button5.Name = "button5";
            this.button5.Size = new System.Drawing.Size(199, 23);
            this.button5.TabIndex = 15;
            this.button5.Text = "Inertial Stabilizers";
            this.button5.UseVisualStyleBackColor = true;
            this.button5.Click += new System.EventHandler(this.Slot2_Click);
            // 
            // button6
            // 
            this.button6.Location = new System.Drawing.Point(421, 77);
            this.button6.Name = "button6";
            this.button6.Size = new System.Drawing.Size(199, 23);
            this.button6.TabIndex = 16;
            this.button6.Text = "Inertial Stabilizers";
            this.button6.UseVisualStyleBackColor = true;
            this.button6.Click += new System.EventHandler(this.Slot3_Click);
            // 
            // button8
            // 
            this.button8.Location = new System.Drawing.Point(217, 106);
            this.button8.Name = "button8";
            this.button8.Size = new System.Drawing.Size(199, 23);
            this.button8.TabIndex = 17;
            this.button8.Text = "Reinforced Bulkheads";
            this.button8.UseVisualStyleBackColor = true;
            this.button8.Click += new System.EventHandler(this.Slot2_Click);
            // 
            // button9
            // 
            this.button9.Location = new System.Drawing.Point(422, 106);
            this.button9.Name = "button9";
            this.button9.Size = new System.Drawing.Size(199, 23);
            this.button9.TabIndex = 18;
            this.button9.Text = "Reinforced Bulkheads";
            this.button9.UseVisualStyleBackColor = true;
            this.button9.Click += new System.EventHandler(this.Slot3_Click);
            // 
            // okButton
            // 
            this.okButton.Location = new System.Drawing.Point(177, 161);
            this.okButton.Name = "okButton";
            this.okButton.Size = new System.Drawing.Size(75, 23);
            this.okButton.TabIndex = 19;
            this.okButton.Text = "OK";
            this.okButton.UseVisualStyleBackColor = true;
            this.okButton.Click += new System.EventHandler(this.OkButton_Click);
            // 
            // cancelButton
            // 
            this.cancelButton.DialogResult = System.Windows.Forms.DialogResult.Cancel;
            this.cancelButton.Location = new System.Drawing.Point(381, 161);
            this.cancelButton.Name = "cancelButton";
            this.cancelButton.Size = new System.Drawing.Size(75, 23);
            this.cancelButton.TabIndex = 20;
            this.cancelButton.Text = "Cancel";
            this.cancelButton.UseVisualStyleBackColor = true;
            // 
            // slot1Text
            // 
            this.slot1Text.Location = new System.Drawing.Point(12, 135);
            this.slot1Text.Name = "slot1Text";
            this.slot1Text.Size = new System.Drawing.Size(199, 20);
            this.slot1Text.TabIndex = 21;
            // 
            // slot2Text
            // 
            this.slot2Text.Location = new System.Drawing.Point(217, 135);
            this.slot2Text.Name = "slot2Text";
            this.slot2Text.Size = new System.Drawing.Size(199, 20);
            this.slot2Text.TabIndex = 22;
            // 
            // slot3Text
            // 
            this.slot3Text.Location = new System.Drawing.Point(422, 135);
            this.slot3Text.Name = "slot3Text";
            this.slot3Text.Size = new System.Drawing.Size(198, 20);
            this.slot3Text.TabIndex = 23;
            // 
            // FitPicker
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.CancelButton = this.cancelButton;
            this.ClientSize = new System.Drawing.Size(632, 193);
            this.Controls.Add(this.slot3Text);
            this.Controls.Add(this.slot2Text);
            this.Controls.Add(this.slot1Text);
            this.Controls.Add(this.cancelButton);
            this.Controls.Add(this.okButton);
            this.Controls.Add(this.button9);
            this.Controls.Add(this.button8);
            this.Controls.Add(this.button6);
            this.Controls.Add(this.button5);
            this.Controls.Add(this.button3);
            this.Controls.Add(this.button2);
            this.Controls.Add(this.label3);
            this.Controls.Add(this.label2);
            this.Controls.Add(this.button7);
            this.Controls.Add(this.button4);
            this.Controls.Add(this.label1);
            this.Controls.Add(this.button1);
            this.Controls.Add(this.menuStrip1);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedToolWindow;
            this.MainMenuStrip = this.menuStrip1;
            this.MaximizeBox = false;
            this.MinimizeBox = false;
            this.Name = "FitPicker";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterParent;
            this.Text = "Freighter Low Slot Picker";
            this.Load += new System.EventHandler(this.FitPicker_Load);
            this.menuStrip1.ResumeLayout(false);
            this.menuStrip1.PerformLayout();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private System.Windows.Forms.MenuStrip menuStrip1;
        private System.Windows.Forms.ToolStripMenuItem xExpandedCargoholdToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem xISTABToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem xATypeAdaptiveNanoPlatingToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem xReinforcedBulkheadsToolStripMenuItem;
        private System.Windows.Forms.Button button1;
        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.Button button4;
        private System.Windows.Forms.Button button7;
        private System.Windows.Forms.Label label2;
        private System.Windows.Forms.Label label3;
        private System.Windows.Forms.Button button2;
        private System.Windows.Forms.Button button3;
        private System.Windows.Forms.Button button5;
        private System.Windows.Forms.Button button6;
        private System.Windows.Forms.Button button8;
        private System.Windows.Forms.Button button9;
        private System.Windows.Forms.Button okButton;
        private System.Windows.Forms.Button cancelButton;
        private System.Windows.Forms.TextBox slot1Text;
        private System.Windows.Forms.TextBox slot2Text;
        private System.Windows.Forms.TextBox slot3Text;
    }
}