// <auto-generated />
namespace EveScanner
{
    partial class Form1
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Form1));
            this.label1 = new System.Windows.Forms.Label();
            this.label2 = new System.Windows.Forms.Label();
            this.label3 = new System.Windows.Forms.Label();
            this.label4 = new System.Windows.Forms.Label();
            this.location1Text = new System.Windows.Forms.TextBox();
            this.location1Radio = new System.Windows.Forms.RadioButton();
            this.location2Radio = new System.Windows.Forms.RadioButton();
            this.location3Radio = new System.Windows.Forms.RadioButton();
            this.location2Text = new System.Windows.Forms.TextBox();
            this.location3Text = new System.Windows.Forms.TextBox();
            this.infoContainer = new System.Windows.Forms.GroupBox();
            this.fitInfoPickerButton = new System.Windows.Forms.Button();
            this.shipTypePickerButton = new System.Windows.Forms.Button();
            this.label9 = new System.Windows.Forms.Label();
            this.notesText = new System.Windows.Forms.TextBox();
            this.label8 = new System.Windows.Forms.Label();
            this.fitInfoText = new System.Windows.Forms.TextBox();
            this.label7 = new System.Windows.Forms.Label();
            this.label6 = new System.Windows.Forms.Label();
            this.characterNameText = new System.Windows.Forms.TextBox();
            this.shipTypeDropdown = new System.Windows.Forms.ComboBox();
            this.locationContainer = new System.Windows.Forms.GroupBox();
            this.scanContainer = new System.Windows.Forms.GroupBox();
            this.submitRequestButton = new System.Windows.Forms.Button();
            this.scanText = new System.Windows.Forms.TextBox();
            this.resultsContainer = new System.Windows.Forms.GroupBox();
            this.historyDropdown = new System.Windows.Forms.ComboBox();
            this.scanValueLabel = new System.Windows.Forms.Label();
            this.label5 = new System.Windows.Forms.Label();
            this.resultUrlTextBox = new System.Windows.Forms.TextBox();
            this.copySummaryButton = new System.Windows.Forms.Button();
            this.sellValueLabel = new System.Windows.Forms.Label();
            this.buyValueLabel = new System.Windows.Forms.Label();
            this.volumeValueLabel = new System.Windows.Forms.Label();
            this.stacksValueText = new System.Windows.Forms.Label();
            this.menuStrip1 = new System.Windows.Forms.MenuStrip();
            this.fileToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.newEmptyScanToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.toolStripSeparator1 = new System.Windows.Forms.ToolStripSeparator();
            this.clearToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.toolStripSeparator2 = new System.Windows.Forms.ToolStripSeparator();
            this.exitToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.showHideExtraOptionsToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.optionsToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.toggleAlwaysOnTopToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.captureClipboardOnToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.submitANYClipboardDataToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.scanSourceToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.evepraisalToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.goonmetricsToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.loggingToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.noneToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.resultsToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.scansAndResultsToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.debugToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.uIToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.hideBordersToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.darkerThemeToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.lighterThemeToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.debugToolStripMenuItem1 = new System.Windows.Forms.ToolStripMenuItem();
            this.addExampleResultsToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.helpToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.aboutToolStripMenuItem1 = new System.Windows.Forms.ToolStripMenuItem();
            this.licenseToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.sourceCodeToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.issueTrackerToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.pictureBox = new System.Windows.Forms.PictureBox();
            this.keepLocationBetweenScansToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.infoContainer.SuspendLayout();
            this.locationContainer.SuspendLayout();
            this.scanContainer.SuspendLayout();
            this.resultsContainer.SuspendLayout();
            this.menuStrip1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox)).BeginInit();
            this.SuspendLayout();
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.Font = new System.Drawing.Font("Microsoft Sans Serif", 32.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label1.Location = new System.Drawing.Point(12, 24);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(107, 51);
            this.label1.TabIndex = 0;
            this.label1.Text = "Sell:";
            // 
            // label2
            // 
            this.label2.AutoSize = true;
            this.label2.Font = new System.Drawing.Font("Microsoft Sans Serif", 24F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label2.Location = new System.Drawing.Point(14, 75);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(80, 37);
            this.label2.TabIndex = 1;
            this.label2.Text = "Buy:";
            // 
            // label3
            // 
            this.label3.AutoSize = true;
            this.label3.Font = new System.Drawing.Font("Microsoft Sans Serif", 15.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label3.Location = new System.Drawing.Point(16, 112);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(90, 25);
            this.label3.TabIndex = 5;
            this.label3.Text = "Volume:";
            // 
            // label4
            // 
            this.label4.AutoSize = true;
            this.label4.Font = new System.Drawing.Font("Microsoft Sans Serif", 15.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label4.Location = new System.Drawing.Point(16, 137);
            this.label4.Name = "label4";
            this.label4.Size = new System.Drawing.Size(83, 25);
            this.label4.TabIndex = 7;
            this.label4.Text = "Stacks:";
            // 
            // location1Text
            // 
            this.location1Text.Location = new System.Drawing.Point(103, 19);
            this.location1Text.Name = "location1Text";
            this.location1Text.Size = new System.Drawing.Size(235, 20);
            this.location1Text.TabIndex = 15;
            this.location1Text.Text = "Perimeter -> Urlen";
            // 
            // location1Radio
            // 
            this.location1Radio.AutoSize = true;
            this.location1Radio.Location = new System.Drawing.Point(6, 20);
            this.location1Radio.Name = "location1Radio";
            this.location1Radio.Size = new System.Drawing.Size(75, 17);
            this.location1Radio.TabIndex = 12;
            this.location1Radio.TabStop = true;
            this.location1Radio.Text = "Location 1";
            this.location1Radio.UseVisualStyleBackColor = true;
            this.location1Radio.Click += new System.EventHandler(this.LocationButton_Click);
            // 
            // location2Radio
            // 
            this.location2Radio.AutoSize = true;
            this.location2Radio.Location = new System.Drawing.Point(6, 46);
            this.location2Radio.Name = "location2Radio";
            this.location2Radio.Size = new System.Drawing.Size(75, 17);
            this.location2Radio.TabIndex = 13;
            this.location2Radio.TabStop = true;
            this.location2Radio.Text = "Location 2";
            this.location2Radio.UseVisualStyleBackColor = true;
            this.location2Radio.Click += new System.EventHandler(this.LocationButton_Click);
            // 
            // location3Radio
            // 
            this.location3Radio.AutoSize = true;
            this.location3Radio.Location = new System.Drawing.Point(6, 72);
            this.location3Radio.Name = "location3Radio";
            this.location3Radio.Size = new System.Drawing.Size(75, 17);
            this.location3Radio.TabIndex = 14;
            this.location3Radio.TabStop = true;
            this.location3Radio.Text = "Location 3";
            this.location3Radio.UseVisualStyleBackColor = true;
            this.location3Radio.Click += new System.EventHandler(this.LocationButton_Click);
            // 
            // location2Text
            // 
            this.location2Text.Location = new System.Drawing.Point(103, 45);
            this.location2Text.Name = "location2Text";
            this.location2Text.Size = new System.Drawing.Size(235, 20);
            this.location2Text.TabIndex = 16;
            this.location2Text.Text = "Ashab -> Madirmilire";
            // 
            // location3Text
            // 
            this.location3Text.Location = new System.Drawing.Point(103, 71);
            this.location3Text.Name = "location3Text";
            this.location3Text.Size = new System.Drawing.Size(235, 20);
            this.location3Text.TabIndex = 17;
            this.location3Text.Text = "Hatakani -> Sivala";
            // 
            // infoContainer
            // 
            this.infoContainer.Controls.Add(this.fitInfoPickerButton);
            this.infoContainer.Controls.Add(this.shipTypePickerButton);
            this.infoContainer.Controls.Add(this.label9);
            this.infoContainer.Controls.Add(this.notesText);
            this.infoContainer.Controls.Add(this.label8);
            this.infoContainer.Controls.Add(this.fitInfoText);
            this.infoContainer.Controls.Add(this.label7);
            this.infoContainer.Controls.Add(this.label6);
            this.infoContainer.Controls.Add(this.characterNameText);
            this.infoContainer.Controls.Add(this.shipTypeDropdown);
            this.infoContainer.Location = new System.Drawing.Point(21, 165);
            this.infoContainer.Name = "infoContainer";
            this.infoContainer.Size = new System.Drawing.Size(350, 174);
            this.infoContainer.TabIndex = 28;
            this.infoContainer.TabStop = false;
            this.infoContainer.Text = "Scan Info";
            // 
            // fitInfoPickerButton
            // 
            this.fitInfoPickerButton.AutoSize = true;
            this.fitInfoPickerButton.Location = new System.Drawing.Point(312, 70);
            this.fitInfoPickerButton.Name = "fitInfoPickerButton";
            this.fitInfoPickerButton.Size = new System.Drawing.Size(26, 23);
            this.fitInfoPickerButton.TabIndex = 38;
            this.fitInfoPickerButton.Text = "...";
            this.fitInfoPickerButton.UseVisualStyleBackColor = true;
            this.fitInfoPickerButton.Click += new System.EventHandler(this.FitInfoPickerButton_Click);
            // 
            // shipTypePickerButton
            // 
            this.shipTypePickerButton.AutoSize = true;
            this.shipTypePickerButton.Location = new System.Drawing.Point(312, 43);
            this.shipTypePickerButton.Name = "shipTypePickerButton";
            this.shipTypePickerButton.Size = new System.Drawing.Size(26, 23);
            this.shipTypePickerButton.TabIndex = 38;
            this.shipTypePickerButton.Text = "...";
            this.shipTypePickerButton.UseVisualStyleBackColor = true;
            this.shipTypePickerButton.Click += new System.EventHandler(this.ShipTypePickerButton_Click);
            // 
            // label9
            // 
            this.label9.AutoSize = true;
            this.label9.Location = new System.Drawing.Point(6, 101);
            this.label9.Name = "label9";
            this.label9.Size = new System.Drawing.Size(35, 13);
            this.label9.TabIndex = 19;
            this.label9.Text = "Notes";
            // 
            // notesText
            // 
            this.notesText.Location = new System.Drawing.Point(103, 98);
            this.notesText.Multiline = true;
            this.notesText.Name = "notesText";
            this.notesText.ScrollBars = System.Windows.Forms.ScrollBars.Both;
            this.notesText.Size = new System.Drawing.Size(235, 70);
            this.notesText.TabIndex = 18;
            this.notesText.Leave += new System.EventHandler(this.NotesText_Leave);
            // 
            // label8
            // 
            this.label8.AutoSize = true;
            this.label8.Location = new System.Drawing.Point(6, 75);
            this.label8.Name = "label8";
            this.label8.Size = new System.Drawing.Size(39, 13);
            this.label8.TabIndex = 17;
            this.label8.Text = "Fit Info";
            // 
            // fitInfoText
            // 
            this.fitInfoText.Location = new System.Drawing.Point(103, 72);
            this.fitInfoText.Name = "fitInfoText";
            this.fitInfoText.Size = new System.Drawing.Size(203, 20);
            this.fitInfoText.TabIndex = 16;
            this.fitInfoText.Leave += new System.EventHandler(this.FitInfoText_Leave);
            // 
            // label7
            // 
            this.label7.AutoSize = true;
            this.label7.Location = new System.Drawing.Point(6, 48);
            this.label7.Name = "label7";
            this.label7.Size = new System.Drawing.Size(55, 13);
            this.label7.TabIndex = 15;
            this.label7.Text = "Ship Type";
            // 
            // label6
            // 
            this.label6.AutoSize = true;
            this.label6.Location = new System.Drawing.Point(6, 22);
            this.label6.Name = "label6";
            this.label6.Size = new System.Drawing.Size(84, 13);
            this.label6.TabIndex = 14;
            this.label6.Text = "Character Name";
            // 
            // characterNameText
            // 
            this.characterNameText.Location = new System.Drawing.Point(103, 19);
            this.characterNameText.Name = "characterNameText";
            this.characterNameText.Size = new System.Drawing.Size(235, 20);
            this.characterNameText.TabIndex = 13;
            this.characterNameText.Leave += new System.EventHandler(this.CharacterNameText_Leave);
            // 
            // shipTypeDropdown
            // 
            this.shipTypeDropdown.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.Suggest;
            this.shipTypeDropdown.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.ListItems;
            this.shipTypeDropdown.FormattingEnabled = true;
            this.shipTypeDropdown.Items.AddRange(new object[] {
            "N/A",
            "Providence",
            "Charon",
            "Obelisk",
            "Fenrir",
            "Ark",
            "Rhea",
            "Anshar",
            "Nomad",
            "Orca",
            "Bowhead"});
            this.shipTypeDropdown.Location = new System.Drawing.Point(103, 45);
            this.shipTypeDropdown.Name = "shipTypeDropdown";
            this.shipTypeDropdown.Size = new System.Drawing.Size(203, 21);
            this.shipTypeDropdown.TabIndex = 14;
            this.shipTypeDropdown.SelectedValueChanged += new System.EventHandler(this.ShipTypeDropdown_SelectedValueChanged);
            // 
            // locationContainer
            // 
            this.locationContainer.Controls.Add(this.location1Radio);
            this.locationContainer.Controls.Add(this.location1Text);
            this.locationContainer.Controls.Add(this.location3Text);
            this.locationContainer.Controls.Add(this.location2Text);
            this.locationContainer.Controls.Add(this.location2Radio);
            this.locationContainer.Controls.Add(this.location3Radio);
            this.locationContainer.Location = new System.Drawing.Point(21, 345);
            this.locationContainer.Name = "locationContainer";
            this.locationContainer.Size = new System.Drawing.Size(350, 104);
            this.locationContainer.TabIndex = 29;
            this.locationContainer.TabStop = false;
            this.locationContainer.Text = "Location";
            // 
            // scanContainer
            // 
            this.scanContainer.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.scanContainer.Controls.Add(this.submitRequestButton);
            this.scanContainer.Controls.Add(this.scanText);
            this.scanContainer.Location = new System.Drawing.Point(377, 165);
            this.scanContainer.Name = "scanContainer";
            this.scanContainer.Size = new System.Drawing.Size(187, 284);
            this.scanContainer.TabIndex = 30;
            this.scanContainer.TabStop = false;
            this.scanContainer.Text = "Raw Scan Data";
            // 
            // submitRequestButton
            // 
            this.submitRequestButton.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.submitRequestButton.Location = new System.Drawing.Point(81, 255);
            this.submitRequestButton.Name = "submitRequestButton";
            this.submitRequestButton.Size = new System.Drawing.Size(100, 23);
            this.submitRequestButton.TabIndex = 22;
            this.submitRequestButton.Text = "Manually Submit";
            this.submitRequestButton.UseVisualStyleBackColor = true;
            this.submitRequestButton.Click += new System.EventHandler(this.SubmitRequestButton_Click);
            // 
            // scanText
            // 
            this.scanText.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.scanText.Location = new System.Drawing.Point(6, 19);
            this.scanText.Multiline = true;
            this.scanText.Name = "scanText";
            this.scanText.ScrollBars = System.Windows.Forms.ScrollBars.Vertical;
            this.scanText.Size = new System.Drawing.Size(175, 230);
            this.scanText.TabIndex = 21;
            // 
            // resultsContainer
            // 
            this.resultsContainer.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.resultsContainer.Controls.Add(this.historyDropdown);
            this.resultsContainer.Controls.Add(this.scanValueLabel);
            this.resultsContainer.Controls.Add(this.label5);
            this.resultsContainer.Controls.Add(this.resultUrlTextBox);
            this.resultsContainer.Controls.Add(this.copySummaryButton);
            this.resultsContainer.Location = new System.Drawing.Point(21, 455);
            this.resultsContainer.Name = "resultsContainer";
            this.resultsContainer.Size = new System.Drawing.Size(543, 75);
            this.resultsContainer.TabIndex = 31;
            this.resultsContainer.TabStop = false;
            this.resultsContainer.Text = "Results";
            // 
            // historyDropdown
            // 
            this.historyDropdown.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.historyDropdown.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.historyDropdown.FormattingEnabled = true;
            this.historyDropdown.Location = new System.Drawing.Point(6, 47);
            this.historyDropdown.Name = "historyDropdown";
            this.historyDropdown.Size = new System.Drawing.Size(372, 21);
            this.historyDropdown.TabIndex = 21;
            this.historyDropdown.SelectedIndexChanged += new System.EventHandler(this.HistoryDropdown_SelectedIndexChanged);
            // 
            // scanValueLabel
            // 
            this.scanValueLabel.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.scanValueLabel.Location = new System.Drawing.Point(437, 45);
            this.scanValueLabel.Name = "scanValueLabel";
            this.scanValueLabel.Size = new System.Drawing.Size(100, 23);
            this.scanValueLabel.TabIndex = 20;
            this.scanValueLabel.Text = "0";
            this.scanValueLabel.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            // 
            // label5
            // 
            this.label5.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.label5.AutoSize = true;
            this.label5.Location = new System.Drawing.Point(391, 50);
            this.label5.Name = "label5";
            this.label5.Size = new System.Drawing.Size(40, 13);
            this.label5.TabIndex = 3;
            this.label5.Text = "Scans:";
            // 
            // resultUrlTextBox
            // 
            this.resultUrlTextBox.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.resultUrlTextBox.Location = new System.Drawing.Point(173, 21);
            this.resultUrlTextBox.Name = "resultUrlTextBox";
            this.resultUrlTextBox.Size = new System.Drawing.Size(364, 20);
            this.resultUrlTextBox.TabIndex = 19;
            // 
            // copySummaryButton
            // 
            this.copySummaryButton.Location = new System.Drawing.Point(6, 19);
            this.copySummaryButton.Name = "copySummaryButton";
            this.copySummaryButton.Size = new System.Drawing.Size(161, 23);
            this.copySummaryButton.TabIndex = 18;
            this.copySummaryButton.Text = "Copy Summary to Clipboard";
            this.copySummaryButton.UseVisualStyleBackColor = true;
            this.copySummaryButton.Click += new System.EventHandler(this.CopySummaryButton_Click);
            // 
            // sellValueLabel
            // 
            this.sellValueLabel.AutoSize = true;
            this.sellValueLabel.Font = new System.Drawing.Font("Microsoft Sans Serif", 32.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.sellValueLabel.Location = new System.Drawing.Point(125, 24);
            this.sellValueLabel.Name = "sellValueLabel";
            this.sellValueLabel.Size = new System.Drawing.Size(64, 51);
            this.sellValueLabel.TabIndex = 32;
            this.sellValueLabel.Text = "---";
            // 
            // buyValueLabel
            // 
            this.buyValueLabel.AutoSize = true;
            this.buyValueLabel.Font = new System.Drawing.Font("Microsoft Sans Serif", 24F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.buyValueLabel.Location = new System.Drawing.Point(127, 75);
            this.buyValueLabel.Name = "buyValueLabel";
            this.buyValueLabel.Size = new System.Drawing.Size(47, 37);
            this.buyValueLabel.TabIndex = 33;
            this.buyValueLabel.Text = "---";
            // 
            // volumeValueLabel
            // 
            this.volumeValueLabel.AutoSize = true;
            this.volumeValueLabel.Font = new System.Drawing.Font("Microsoft Sans Serif", 15.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.volumeValueLabel.Location = new System.Drawing.Point(129, 112);
            this.volumeValueLabel.Name = "volumeValueLabel";
            this.volumeValueLabel.Size = new System.Drawing.Size(33, 25);
            this.volumeValueLabel.TabIndex = 34;
            this.volumeValueLabel.Text = "---";
            // 
            // stacksValueText
            // 
            this.stacksValueText.AutoSize = true;
            this.stacksValueText.Font = new System.Drawing.Font("Microsoft Sans Serif", 15.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.stacksValueText.Location = new System.Drawing.Point(129, 137);
            this.stacksValueText.Name = "stacksValueText";
            this.stacksValueText.Size = new System.Drawing.Size(33, 25);
            this.stacksValueText.TabIndex = 35;
            this.stacksValueText.Text = "---";
            // 
            // menuStrip1
            // 
            this.menuStrip1.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.fileToolStripMenuItem,
            this.showHideExtraOptionsToolStripMenuItem,
            this.optionsToolStripMenuItem,
            this.helpToolStripMenuItem});
            this.menuStrip1.Location = new System.Drawing.Point(0, 0);
            this.menuStrip1.Name = "menuStrip1";
            this.menuStrip1.Size = new System.Drawing.Size(574, 24);
            this.menuStrip1.TabIndex = 36;
            this.menuStrip1.Text = "menuStrip1";
            // 
            // fileToolStripMenuItem
            // 
            this.fileToolStripMenuItem.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.newEmptyScanToolStripMenuItem,
            this.toolStripSeparator1,
            this.clearToolStripMenuItem,
            this.toolStripSeparator2,
            this.exitToolStripMenuItem});
            this.fileToolStripMenuItem.Name = "fileToolStripMenuItem";
            this.fileToolStripMenuItem.Size = new System.Drawing.Size(37, 20);
            this.fileToolStripMenuItem.Text = "&File";
            // 
            // newEmptyScanToolStripMenuItem
            // 
            this.newEmptyScanToolStripMenuItem.Name = "newEmptyScanToolStripMenuItem";
            this.newEmptyScanToolStripMenuItem.Size = new System.Drawing.Size(163, 22);
            this.newEmptyScanToolStripMenuItem.Text = "New Empty Scan";
            this.newEmptyScanToolStripMenuItem.Click += new System.EventHandler(this.NewEmptyScanToolStripMenuItem_Click);
            // 
            // toolStripSeparator1
            // 
            this.toolStripSeparator1.Name = "toolStripSeparator1";
            this.toolStripSeparator1.Size = new System.Drawing.Size(160, 6);
            // 
            // clearToolStripMenuItem
            // 
            this.clearToolStripMenuItem.Name = "clearToolStripMenuItem";
            this.clearToolStripMenuItem.Size = new System.Drawing.Size(163, 22);
            this.clearToolStripMenuItem.Text = "&Reset Data";
            this.clearToolStripMenuItem.Click += new System.EventHandler(this.ClearToolStripMenuItem_Click);
            // 
            // toolStripSeparator2
            // 
            this.toolStripSeparator2.Name = "toolStripSeparator2";
            this.toolStripSeparator2.Size = new System.Drawing.Size(160, 6);
            // 
            // exitToolStripMenuItem
            // 
            this.exitToolStripMenuItem.Name = "exitToolStripMenuItem";
            this.exitToolStripMenuItem.Size = new System.Drawing.Size(163, 22);
            this.exitToolStripMenuItem.Text = "E&xit";
            this.exitToolStripMenuItem.Click += new System.EventHandler(this.ExitToolStripMenuItem_Click);
            // 
            // showHideExtraOptionsToolStripMenuItem
            // 
            this.showHideExtraOptionsToolStripMenuItem.Name = "showHideExtraOptionsToolStripMenuItem";
            this.showHideExtraOptionsToolStripMenuItem.Size = new System.Drawing.Size(150, 20);
            this.showHideExtraOptionsToolStripMenuItem.Text = "Show/Hide Extra &Buttons";
            this.showHideExtraOptionsToolStripMenuItem.Click += new System.EventHandler(this.ShowHideExtraOptionsToolStripMenuItem_Click);
            // 
            // optionsToolStripMenuItem
            // 
            this.optionsToolStripMenuItem.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.toggleAlwaysOnTopToolStripMenuItem,
            this.captureClipboardOnToolStripMenuItem,
            this.submitANYClipboardDataToolStripMenuItem,
            this.keepLocationBetweenScansToolStripMenuItem,
            this.scanSourceToolStripMenuItem,
            this.loggingToolStripMenuItem,
            this.uIToolStripMenuItem,
            this.debugToolStripMenuItem1});
            this.optionsToolStripMenuItem.Name = "optionsToolStripMenuItem";
            this.optionsToolStripMenuItem.Size = new System.Drawing.Size(61, 20);
            this.optionsToolStripMenuItem.Text = "&Options";
            // 
            // toggleAlwaysOnTopToolStripMenuItem
            // 
            this.toggleAlwaysOnTopToolStripMenuItem.Name = "toggleAlwaysOnTopToolStripMenuItem";
            this.toggleAlwaysOnTopToolStripMenuItem.Size = new System.Drawing.Size(230, 22);
            this.toggleAlwaysOnTopToolStripMenuItem.Text = "&Toggle Always on Top";
            this.toggleAlwaysOnTopToolStripMenuItem.Click += new System.EventHandler(this.ToggleAlwaysOnTopToolStripMenuItem_Click);
            // 
            // captureClipboardOnToolStripMenuItem
            // 
            this.captureClipboardOnToolStripMenuItem.Name = "captureClipboardOnToolStripMenuItem";
            this.captureClipboardOnToolStripMenuItem.Size = new System.Drawing.Size(230, 22);
            this.captureClipboardOnToolStripMenuItem.Text = "&Capture Clipboard";
            this.captureClipboardOnToolStripMenuItem.Click += new System.EventHandler(this.CaptureClipboardOnToolStripMenuItem_Click);
            // 
            // submitANYClipboardDataToolStripMenuItem
            // 
            this.submitANYClipboardDataToolStripMenuItem.Name = "submitANYClipboardDataToolStripMenuItem";
            this.submitANYClipboardDataToolStripMenuItem.Size = new System.Drawing.Size(230, 22);
            this.submitANYClipboardDataToolStripMenuItem.Text = "Submit &ANY Clipboard Data";
            this.submitANYClipboardDataToolStripMenuItem.Click += new System.EventHandler(this.SubmitANYClipboardDataToolStripMenuItem_Click);
            // 
            // scanSourceToolStripMenuItem
            // 
            this.scanSourceToolStripMenuItem.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.evepraisalToolStripMenuItem,
            this.goonmetricsToolStripMenuItem});
            this.scanSourceToolStripMenuItem.Name = "scanSourceToolStripMenuItem";
            this.scanSourceToolStripMenuItem.Size = new System.Drawing.Size(230, 22);
            this.scanSourceToolStripMenuItem.Text = "&Scan Source";
            // 
            // evepraisalToolStripMenuItem
            // 
            this.evepraisalToolStripMenuItem.Checked = true;
            this.evepraisalToolStripMenuItem.CheckState = System.Windows.Forms.CheckState.Checked;
            this.evepraisalToolStripMenuItem.Name = "evepraisalToolStripMenuItem";
            this.evepraisalToolStripMenuItem.Size = new System.Drawing.Size(152, 22);
            this.evepraisalToolStripMenuItem.Tag = "Evepraisal";
            this.evepraisalToolStripMenuItem.Text = "Evepraisal";
            this.evepraisalToolStripMenuItem.Click += new System.EventHandler(this.ScanSourceStripMenu_Click);
            // 
            // goonmetricsToolStripMenuItem
            // 
            this.goonmetricsToolStripMenuItem.Name = "goonmetricsToolStripMenuItem";
            this.goonmetricsToolStripMenuItem.Size = new System.Drawing.Size(152, 22);
            this.goonmetricsToolStripMenuItem.Tag = "Goonmetrics";
            this.goonmetricsToolStripMenuItem.Text = "Goonmetrics";
            this.goonmetricsToolStripMenuItem.Click += new System.EventHandler(this.ScanSourceStripMenu_Click);
            // 
            // loggingToolStripMenuItem
            // 
            this.loggingToolStripMenuItem.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.noneToolStripMenuItem,
            this.resultsToolStripMenuItem,
            this.scansAndResultsToolStripMenuItem,
            this.debugToolStripMenuItem});
            this.loggingToolStripMenuItem.Name = "loggingToolStripMenuItem";
            this.loggingToolStripMenuItem.Size = new System.Drawing.Size(230, 22);
            this.loggingToolStripMenuItem.Text = "&Logging";
            // 
            // noneToolStripMenuItem
            // 
            this.noneToolStripMenuItem.Checked = true;
            this.noneToolStripMenuItem.CheckState = System.Windows.Forms.CheckState.Checked;
            this.noneToolStripMenuItem.Name = "noneToolStripMenuItem";
            this.noneToolStripMenuItem.Size = new System.Drawing.Size(167, 22);
            this.noneToolStripMenuItem.Tag = "none";
            this.noneToolStripMenuItem.Text = "&None";
            this.noneToolStripMenuItem.Click += new System.EventHandler(this.DebugLevelStripMenu_Click);
            // 
            // resultsToolStripMenuItem
            // 
            this.resultsToolStripMenuItem.Name = "resultsToolStripMenuItem";
            this.resultsToolStripMenuItem.Size = new System.Drawing.Size(167, 22);
            this.resultsToolStripMenuItem.Tag = "results";
            this.resultsToolStripMenuItem.Text = "&Results";
            this.resultsToolStripMenuItem.Click += new System.EventHandler(this.DebugLevelStripMenu_Click);
            // 
            // scansAndResultsToolStripMenuItem
            // 
            this.scansAndResultsToolStripMenuItem.Name = "scansAndResultsToolStripMenuItem";
            this.scansAndResultsToolStripMenuItem.Size = new System.Drawing.Size(167, 22);
            this.scansAndResultsToolStripMenuItem.Tag = "scans";
            this.scansAndResultsToolStripMenuItem.Text = "&Scans and Results";
            this.scansAndResultsToolStripMenuItem.Click += new System.EventHandler(this.DebugLevelStripMenu_Click);
            // 
            // debugToolStripMenuItem
            // 
            this.debugToolStripMenuItem.Name = "debugToolStripMenuItem";
            this.debugToolStripMenuItem.Size = new System.Drawing.Size(167, 22);
            this.debugToolStripMenuItem.Tag = "debug";
            this.debugToolStripMenuItem.Text = "&Debug";
            this.debugToolStripMenuItem.Click += new System.EventHandler(this.DebugLevelStripMenu_Click);
            // 
            // uIToolStripMenuItem
            // 
            this.uIToolStripMenuItem.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.hideBordersToolStripMenuItem,
            this.darkerThemeToolStripMenuItem,
            this.lighterThemeToolStripMenuItem});
            this.uIToolStripMenuItem.Name = "uIToolStripMenuItem";
            this.uIToolStripMenuItem.Size = new System.Drawing.Size(230, 22);
            this.uIToolStripMenuItem.Text = "&UI";
            // 
            // hideBordersToolStripMenuItem
            // 
            this.hideBordersToolStripMenuItem.Name = "hideBordersToolStripMenuItem";
            this.hideBordersToolStripMenuItem.ShortcutKeys = ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.B)));
            this.hideBordersToolStripMenuItem.Size = new System.Drawing.Size(191, 22);
            this.hideBordersToolStripMenuItem.Text = "Hide Borders";
            this.hideBordersToolStripMenuItem.Click += new System.EventHandler(this.HideBordersToolStripMenuItem_Click);
            // 
            // darkerThemeToolStripMenuItem
            // 
            this.darkerThemeToolStripMenuItem.Name = "darkerThemeToolStripMenuItem";
            this.darkerThemeToolStripMenuItem.ShortcutKeys = ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.D)));
            this.darkerThemeToolStripMenuItem.Size = new System.Drawing.Size(191, 22);
            this.darkerThemeToolStripMenuItem.Text = "Darker Theme";
            this.darkerThemeToolStripMenuItem.Click += new System.EventHandler(this.DarkerThemeToolStripMenuItem_Click);
            // 
            // lighterThemeToolStripMenuItem
            // 
            this.lighterThemeToolStripMenuItem.Name = "lighterThemeToolStripMenuItem";
            this.lighterThemeToolStripMenuItem.ShortcutKeys = ((System.Windows.Forms.Keys)((System.Windows.Forms.Keys.Control | System.Windows.Forms.Keys.L)));
            this.lighterThemeToolStripMenuItem.Size = new System.Drawing.Size(191, 22);
            this.lighterThemeToolStripMenuItem.Text = "Lighter Theme";
            this.lighterThemeToolStripMenuItem.Click += new System.EventHandler(this.LighterThemeToolStripMenuItem_Click);
            // 
            // debugToolStripMenuItem1
            // 
            this.debugToolStripMenuItem1.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.addExampleResultsToolStripMenuItem});
            this.debugToolStripMenuItem1.Name = "debugToolStripMenuItem1";
            this.debugToolStripMenuItem1.Size = new System.Drawing.Size(230, 22);
            this.debugToolStripMenuItem1.Text = "Debug";
            // 
            // addExampleResultsToolStripMenuItem
            // 
            this.addExampleResultsToolStripMenuItem.Name = "addExampleResultsToolStripMenuItem";
            this.addExampleResultsToolStripMenuItem.Size = new System.Drawing.Size(297, 22);
            this.addExampleResultsToolStripMenuItem.Text = "Show Example Results (Clears Current List)";
            this.addExampleResultsToolStripMenuItem.Click += new System.EventHandler(this.AddExampleResultsToolStripMenuItem_Click);
            // 
            // helpToolStripMenuItem
            // 
            this.helpToolStripMenuItem.Alignment = System.Windows.Forms.ToolStripItemAlignment.Right;
            this.helpToolStripMenuItem.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.aboutToolStripMenuItem1,
            this.licenseToolStripMenuItem,
            this.sourceCodeToolStripMenuItem,
            this.issueTrackerToolStripMenuItem});
            this.helpToolStripMenuItem.Name = "helpToolStripMenuItem";
            this.helpToolStripMenuItem.Size = new System.Drawing.Size(44, 20);
            this.helpToolStripMenuItem.Text = "&Help";
            // 
            // aboutToolStripMenuItem1
            // 
            this.aboutToolStripMenuItem1.Name = "aboutToolStripMenuItem1";
            this.aboutToolStripMenuItem1.Size = new System.Drawing.Size(245, 22);
            this.aboutToolStripMenuItem1.Text = "&About";
            this.aboutToolStripMenuItem1.Click += new System.EventHandler(this.AboutToolStripMenuItem_Click);
            // 
            // licenseToolStripMenuItem
            // 
            this.licenseToolStripMenuItem.Name = "licenseToolStripMenuItem";
            this.licenseToolStripMenuItem.Size = new System.Drawing.Size(245, 22);
            this.licenseToolStripMenuItem.Text = "&License";
            this.licenseToolStripMenuItem.Click += new System.EventHandler(this.LicenseToolStripMenuItem_Click);
            // 
            // sourceCodeToolStripMenuItem
            // 
            this.sourceCodeToolStripMenuItem.Name = "sourceCodeToolStripMenuItem";
            this.sourceCodeToolStripMenuItem.Size = new System.Drawing.Size(245, 22);
            this.sourceCodeToolStripMenuItem.Text = "&Source Code (Opens in Browser)";
            this.sourceCodeToolStripMenuItem.Click += new System.EventHandler(this.SourceCodeToolStripMenuItem_Click);
            // 
            // issueTrackerToolStripMenuItem
            // 
            this.issueTrackerToolStripMenuItem.Name = "issueTrackerToolStripMenuItem";
            this.issueTrackerToolStripMenuItem.Size = new System.Drawing.Size(245, 22);
            this.issueTrackerToolStripMenuItem.Text = "&Issue Tracker (Opens in Browser)";
            this.issueTrackerToolStripMenuItem.Click += new System.EventHandler(this.IssueTrackerToolStripMenuItem_Click);
            // 
            // pictureBox
            // 
            this.pictureBox.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.pictureBox.Location = new System.Drawing.Point(415, 24);
            this.pictureBox.Name = "pictureBox";
            this.pictureBox.Size = new System.Drawing.Size(149, 135);
            this.pictureBox.SizeMode = System.Windows.Forms.PictureBoxSizeMode.CenterImage;
            this.pictureBox.TabIndex = 37;
            this.pictureBox.TabStop = false;
            // 
            // keepLocationBetweenScansToolStripMenuItem
            // 
            this.keepLocationBetweenScansToolStripMenuItem.Name = "keepLocationBetweenScansToolStripMenuItem";
            this.keepLocationBetweenScansToolStripMenuItem.Size = new System.Drawing.Size(230, 22);
            this.keepLocationBetweenScansToolStripMenuItem.Text = "Keep Location between Scans";
            this.keepLocationBetweenScansToolStripMenuItem.Click += new System.EventHandler(this.KeepLocationBetweenScansToolStripMenuItem_Click);
            // 
            // Form1
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(574, 535);
            this.Controls.Add(this.pictureBox);
            this.Controls.Add(this.stacksValueText);
            this.Controls.Add(this.volumeValueLabel);
            this.Controls.Add(this.buyValueLabel);
            this.Controls.Add(this.sellValueLabel);
            this.Controls.Add(this.resultsContainer);
            this.Controls.Add(this.scanContainer);
            this.Controls.Add(this.locationContainer);
            this.Controls.Add(this.infoContainer);
            this.Controls.Add(this.label4);
            this.Controls.Add(this.label3);
            this.Controls.Add(this.label2);
            this.Controls.Add(this.label1);
            this.Controls.Add(this.menuStrip1);
            this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
            this.MainMenuStrip = this.menuStrip1;
            this.MinimumSize = new System.Drawing.Size(590, 520);
            this.Name = "Form1";
            this.Text = "I LOVE SCANNING";
            this.FormClosing += new System.Windows.Forms.FormClosingEventHandler(this.Form1_FormClosing);
            this.Load += new System.EventHandler(this.Form1_Load);
            this.infoContainer.ResumeLayout(false);
            this.infoContainer.PerformLayout();
            this.locationContainer.ResumeLayout(false);
            this.locationContainer.PerformLayout();
            this.scanContainer.ResumeLayout(false);
            this.scanContainer.PerformLayout();
            this.resultsContainer.ResumeLayout(false);
            this.resultsContainer.PerformLayout();
            this.menuStrip1.ResumeLayout(false);
            this.menuStrip1.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.Label label2;
        private System.Windows.Forms.Label label3;
        private System.Windows.Forms.Label label4;
        private System.Windows.Forms.TextBox location1Text;
        private System.Windows.Forms.RadioButton location1Radio;
        private System.Windows.Forms.RadioButton location2Radio;
        private System.Windows.Forms.RadioButton location3Radio;
        private System.Windows.Forms.TextBox location2Text;
        private System.Windows.Forms.TextBox location3Text;
        private System.Windows.Forms.GroupBox infoContainer;
        private System.Windows.Forms.GroupBox locationContainer;
        private System.Windows.Forms.GroupBox scanContainer;
        private System.Windows.Forms.TextBox scanText;
        private System.Windows.Forms.GroupBox resultsContainer;
        private System.Windows.Forms.Label label5;
        private System.Windows.Forms.TextBox resultUrlTextBox;
        private System.Windows.Forms.Button copySummaryButton;
        private System.Windows.Forms.Label sellValueLabel;
        private System.Windows.Forms.Label buyValueLabel;
        private System.Windows.Forms.Label volumeValueLabel;
        private System.Windows.Forms.Label stacksValueText;
        private System.Windows.Forms.MenuStrip menuStrip1;
        private System.Windows.Forms.ToolStripMenuItem fileToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem exitToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem showHideExtraOptionsToolStripMenuItem;
        private System.Windows.Forms.Button submitRequestButton;
        private System.Windows.Forms.ToolStripMenuItem toggleAlwaysOnTopToolStripMenuItem;
        private System.Windows.Forms.Label scanValueLabel;
        private System.Windows.Forms.ComboBox historyDropdown;
        private System.Windows.Forms.ToolStripMenuItem captureClipboardOnToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem clearToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem optionsToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem loggingToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem noneToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem resultsToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem scansAndResultsToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem debugToolStripMenuItem;
        private System.Windows.Forms.PictureBox pictureBox;
        private System.Windows.Forms.ToolStripMenuItem scanSourceToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem evepraisalToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem goonmetricsToolStripMenuItem;
        private System.Windows.Forms.ComboBox shipTypeDropdown;
        private System.Windows.Forms.Label label7;
        private System.Windows.Forms.Label label6;
        private System.Windows.Forms.TextBox characterNameText;
        private System.Windows.Forms.Label label9;
        private System.Windows.Forms.TextBox notesText;
        private System.Windows.Forms.Label label8;
        private System.Windows.Forms.TextBox fitInfoText;
        private System.Windows.Forms.ToolStripMenuItem submitANYClipboardDataToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem debugToolStripMenuItem1;
        private System.Windows.Forms.ToolStripMenuItem addExampleResultsToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem helpToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem licenseToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem aboutToolStripMenuItem1;
        private System.Windows.Forms.ToolStripMenuItem sourceCodeToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem issueTrackerToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem uIToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem hideBordersToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem darkerThemeToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem newEmptyScanToolStripMenuItem;
        private System.Windows.Forms.ToolStripSeparator toolStripSeparator1;
        private System.Windows.Forms.ToolStripSeparator toolStripSeparator2;
        private System.Windows.Forms.ToolStripMenuItem lighterThemeToolStripMenuItem;
        private System.Windows.Forms.Button fitInfoPickerButton;
        private System.Windows.Forms.Button shipTypePickerButton;
        private System.Windows.Forms.ToolStripMenuItem keepLocationBetweenScansToolStripMenuItem;
    }
}

