// <auto-generated />
namespace EveScanner.UI
{
    partial class EmploymentHistory
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.employmentHistoryListbox1 = new EveScanner.UI.EmploymentHistoryListbox();
            this.SuspendLayout();
            // 
            // employmentHistoryListbox1
            // 
            this.employmentHistoryListbox1.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.employmentHistoryListbox1.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.employmentHistoryListbox1.FormattingEnabled = true;
            this.employmentHistoryListbox1.ItemHeight = 64;
            this.employmentHistoryListbox1.Location = new System.Drawing.Point(12, 12);
            this.employmentHistoryListbox1.Name = "employmentHistoryListbox1";
            this.employmentHistoryListbox1.Size = new System.Drawing.Size(629, 388);
            this.employmentHistoryListbox1.TabIndex = 3;
            // 
            // EmploymentHistory
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(653, 410);
            this.Controls.Add(this.employmentHistoryListbox1);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedToolWindow;
            this.MaximizeBox = false;
            this.MinimizeBox = false;
            this.Name = "EmploymentHistory";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterParent;
            this.Text = "Employment History";
            this.ResumeLayout(false);

        }

        #endregion

        private EmploymentHistoryListbox employmentHistoryListbox1;
    }
}

