// <auto-generated />
namespace EveScanner
{
    partial class ScanHistory
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.scanHistoryGrid = new System.Windows.Forms.DataGridView();
            this.okButton = new System.Windows.Forms.Button();
            this.cancelButton = new System.Windows.Forms.Button();
            this.characterFilterButton = new System.Windows.Forms.Button();
            this.label1 = new System.Windows.Forms.Label();
            this.characterName = new System.Windows.Forms.TextBox();
            ((System.ComponentModel.ISupportInitialize)(this.scanHistoryGrid)).BeginInit();
            this.SuspendLayout();
            // 
            // dataGridView1
            // 
            this.scanHistoryGrid.AllowUserToAddRows = false;
            this.scanHistoryGrid.AllowUserToDeleteRows = false;
            this.scanHistoryGrid.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.scanHistoryGrid.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            this.scanHistoryGrid.Location = new System.Drawing.Point(12, 41);
            this.scanHistoryGrid.Name = "dataGridView1";
            this.scanHistoryGrid.Size = new System.Drawing.Size(714, 323);
            this.scanHistoryGrid.TabIndex = 0;
            this.scanHistoryGrid.CellDoubleClick += new System.Windows.Forms.DataGridViewCellEventHandler(this.Grid_CellDoubleClick);
            this.scanHistoryGrid.RowHeaderMouseDoubleClick += new System.Windows.Forms.DataGridViewCellMouseEventHandler(this.Grid_RowHeaderMouseDoubleClick);
            // 
            // okButton
            // 
            this.okButton.Anchor = System.Windows.Forms.AnchorStyles.Bottom;
            this.okButton.Location = new System.Drawing.Point(199, 370);
            this.okButton.Name = "okButton";
            this.okButton.Size = new System.Drawing.Size(75, 23);
            this.okButton.TabIndex = 1;
            this.okButton.Text = "Copy to App";
            this.okButton.UseVisualStyleBackColor = true;
            this.okButton.Click += new System.EventHandler(this.OkButton_Click);
            // 
            // cancelButton
            // 
            this.cancelButton.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.cancelButton.Location = new System.Drawing.Point(533, 370);
            this.cancelButton.Name = "cancelButton";
            this.cancelButton.Size = new System.Drawing.Size(75, 23);
            this.cancelButton.TabIndex = 2;
            this.cancelButton.Text = "Cancel";
            this.cancelButton.UseVisualStyleBackColor = true;
            this.cancelButton.Click += new System.EventHandler(this.CancelButton_Click);
            // 
            // characterFilterButton
            // 
            this.characterFilterButton.Location = new System.Drawing.Point(274, 12);
            this.characterFilterButton.Name = "characterFilterButton";
            this.characterFilterButton.Size = new System.Drawing.Size(75, 23);
            this.characterFilterButton.TabIndex = 3;
            this.characterFilterButton.Text = "Filter";
            this.characterFilterButton.UseVisualStyleBackColor = true;
            this.characterFilterButton.Click += new System.EventHandler(this.CharacterFilter_Click);
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.Location = new System.Drawing.Point(27, 17);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(87, 13);
            this.label1.TabIndex = 4;
            this.label1.Text = "Character Name:";
            // 
            // characterName
            // 
            this.characterName.Location = new System.Drawing.Point(120, 14);
            this.characterName.Name = "characterName";
            this.characterName.Size = new System.Drawing.Size(148, 20);
            this.characterName.TabIndex = 5;
            // 
            // ScanHistory
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(738, 401);
            this.Controls.Add(this.characterName);
            this.Controls.Add(this.label1);
            this.Controls.Add(this.characterFilterButton);
            this.Controls.Add(this.cancelButton);
            this.Controls.Add(this.okButton);
            this.Controls.Add(this.scanHistoryGrid);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedToolWindow;
            this.MaximizeBox = false;
            this.MinimizeBox = false;
            this.Name = "ScanHistory";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterParent;
            this.Text = "Scan History";
            this.Load += new System.EventHandler(this.ScanHistory_Load);
            ((System.ComponentModel.ISupportInitialize)(this.scanHistoryGrid)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private System.Windows.Forms.DataGridView scanHistoryGrid;
        private System.Windows.Forms.Button okButton;
        private System.Windows.Forms.Button cancelButton;
        private System.Windows.Forms.Button characterFilterButton;
        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.TextBox characterName;

    }
}