// <auto-generated />
namespace EveScanner.UI
{
    partial class StandingsForm
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.label1 = new System.Windows.Forms.Label();
            this.derivedValue = new System.Windows.Forms.Label();
            this.label3 = new System.Windows.Forms.Label();
            this.personalCharacterValue = new System.Windows.Forms.Label();
            this.label5 = new System.Windows.Forms.Label();
            this.personalCorporationValue = new System.Windows.Forms.Label();
            this.label7 = new System.Windows.Forms.Label();
            this.personalAllianceValue = new System.Windows.Forms.Label();
            this.corporationCharacterValue = new System.Windows.Forms.Label();
            this.label10 = new System.Windows.Forms.Label();
            this.corporationCorporationValue = new System.Windows.Forms.Label();
            this.label12 = new System.Windows.Forms.Label();
            this.corporationAllianceValue = new System.Windows.Forms.Label();
            this.label14 = new System.Windows.Forms.Label();
            this.allianceAllianceValue = new System.Windows.Forms.Label();
            this.label16 = new System.Windows.Forms.Label();
            this.allianceCorporationValue = new System.Windows.Forms.Label();
            this.label18 = new System.Windows.Forms.Label();
            this.allianceCharacterValue = new System.Windows.Forms.Label();
            this.label20 = new System.Windows.Forms.Label();
            this.SuspendLayout();
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.Location = new System.Drawing.Point(12, 15);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(97, 13);
            this.label1.TabIndex = 1;
            this.label1.Text = "Derived Standings:";
            // 
            // derivedValue
            // 
            this.derivedValue.AutoSize = true;
            this.derivedValue.Location = new System.Drawing.Point(159, 15);
            this.derivedValue.Name = "derivedValue";
            this.derivedValue.Size = new System.Drawing.Size(28, 13);
            this.derivedValue.TabIndex = 2;
            this.derivedValue.Text = "0.00";
            // 
            // label3
            // 
            this.label3.AutoSize = true;
            this.label3.Location = new System.Drawing.Point(12, 41);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(109, 13);
            this.label3.TabIndex = 3;
            this.label3.Text = "Personal -> Character";
            // 
            // personalCharacterValue
            // 
            this.personalCharacterValue.AutoSize = true;
            this.personalCharacterValue.Location = new System.Drawing.Point(159, 41);
            this.personalCharacterValue.Name = "personalCharacterValue";
            this.personalCharacterValue.Size = new System.Drawing.Size(28, 13);
            this.personalCharacterValue.TabIndex = 4;
            this.personalCharacterValue.Text = "0.00";
            // 
            // label5
            // 
            this.label5.AutoSize = true;
            this.label5.Location = new System.Drawing.Point(12, 67);
            this.label5.Name = "label5";
            this.label5.Size = new System.Drawing.Size(117, 13);
            this.label5.TabIndex = 7;
            this.label5.Text = "Personal -> Corporation";
            // 
            // personalCorporationValue
            // 
            this.personalCorporationValue.AutoSize = true;
            this.personalCorporationValue.Location = new System.Drawing.Point(159, 67);
            this.personalCorporationValue.Name = "personalCorporationValue";
            this.personalCorporationValue.Size = new System.Drawing.Size(28, 13);
            this.personalCorporationValue.TabIndex = 8;
            this.personalCorporationValue.Text = "0.00";
            // 
            // label7
            // 
            this.label7.AutoSize = true;
            this.label7.Location = new System.Drawing.Point(12, 93);
            this.label7.Name = "label7";
            this.label7.Size = new System.Drawing.Size(100, 13);
            this.label7.TabIndex = 9;
            this.label7.Text = "Personal -> Alliance";
            // 
            // personalAllianceValue
            // 
            this.personalAllianceValue.AutoSize = true;
            this.personalAllianceValue.Location = new System.Drawing.Point(159, 93);
            this.personalAllianceValue.Name = "personalAllianceValue";
            this.personalAllianceValue.Size = new System.Drawing.Size(28, 13);
            this.personalAllianceValue.TabIndex = 10;
            this.personalAllianceValue.Text = "0.00";
            // 
            // corporationCharacterValue
            // 
            this.corporationCharacterValue.AutoSize = true;
            this.corporationCharacterValue.Location = new System.Drawing.Point(376, 41);
            this.corporationCharacterValue.Name = "corporationCharacterValue";
            this.corporationCharacterValue.Size = new System.Drawing.Size(28, 13);
            this.corporationCharacterValue.TabIndex = 12;
            this.corporationCharacterValue.Text = "0.00";
            // 
            // label10
            // 
            this.label10.AutoSize = true;
            this.label10.Location = new System.Drawing.Point(229, 41);
            this.label10.Name = "label10";
            this.label10.Size = new System.Drawing.Size(122, 13);
            this.label10.TabIndex = 11;
            this.label10.Text = "Corporation -> Character";
            // 
            // corporationCorporationValue
            // 
            this.corporationCorporationValue.AutoSize = true;
            this.corporationCorporationValue.Location = new System.Drawing.Point(376, 67);
            this.corporationCorporationValue.Name = "corporationCorporationValue";
            this.corporationCorporationValue.Size = new System.Drawing.Size(28, 13);
            this.corporationCorporationValue.TabIndex = 14;
            this.corporationCorporationValue.Text = "0.00";
            // 
            // label12
            // 
            this.label12.AutoSize = true;
            this.label12.Location = new System.Drawing.Point(229, 67);
            this.label12.Name = "label12";
            this.label12.Size = new System.Drawing.Size(130, 13);
            this.label12.TabIndex = 13;
            this.label12.Text = "Corporation -> Corporation";
            // 
            // corporationAllianceValue
            // 
            this.corporationAllianceValue.AutoSize = true;
            this.corporationAllianceValue.Location = new System.Drawing.Point(376, 93);
            this.corporationAllianceValue.Name = "corporationAllianceValue";
            this.corporationAllianceValue.Size = new System.Drawing.Size(28, 13);
            this.corporationAllianceValue.TabIndex = 16;
            this.corporationAllianceValue.Text = "0.00";
            // 
            // label14
            // 
            this.label14.AutoSize = true;
            this.label14.Location = new System.Drawing.Point(229, 93);
            this.label14.Name = "label14";
            this.label14.Size = new System.Drawing.Size(113, 13);
            this.label14.TabIndex = 15;
            this.label14.Text = "Corporation -> Alliance";
            // 
            // allianceAllianceValue
            // 
            this.allianceAllianceValue.AutoSize = true;
            this.allianceAllianceValue.Location = new System.Drawing.Point(595, 93);
            this.allianceAllianceValue.Name = "allianceAllianceValue";
            this.allianceAllianceValue.Size = new System.Drawing.Size(28, 13);
            this.allianceAllianceValue.TabIndex = 22;
            this.allianceAllianceValue.Text = "0.00";
            // 
            // label16
            // 
            this.label16.AutoSize = true;
            this.label16.Location = new System.Drawing.Point(448, 93);
            this.label16.Name = "label16";
            this.label16.Size = new System.Drawing.Size(96, 13);
            this.label16.TabIndex = 21;
            this.label16.Text = "Alliance -> Alliance";
            // 
            // allianceCorporationValue
            // 
            this.allianceCorporationValue.AutoSize = true;
            this.allianceCorporationValue.Location = new System.Drawing.Point(595, 67);
            this.allianceCorporationValue.Name = "allianceCorporationValue";
            this.allianceCorporationValue.Size = new System.Drawing.Size(28, 13);
            this.allianceCorporationValue.TabIndex = 20;
            this.allianceCorporationValue.Text = "0.00";
            // 
            // label18
            // 
            this.label18.AutoSize = true;
            this.label18.Location = new System.Drawing.Point(448, 67);
            this.label18.Name = "label18";
            this.label18.Size = new System.Drawing.Size(113, 13);
            this.label18.TabIndex = 19;
            this.label18.Text = "Alliance -> Corporation";
            // 
            // allianceCharacterValue
            // 
            this.allianceCharacterValue.AutoSize = true;
            this.allianceCharacterValue.Location = new System.Drawing.Point(595, 41);
            this.allianceCharacterValue.Name = "allianceCharacterValue";
            this.allianceCharacterValue.Size = new System.Drawing.Size(28, 13);
            this.allianceCharacterValue.TabIndex = 18;
            this.allianceCharacterValue.Text = "0.00";
            // 
            // label20
            // 
            this.label20.AutoSize = true;
            this.label20.Location = new System.Drawing.Point(448, 41);
            this.label20.Name = "label20";
            this.label20.Size = new System.Drawing.Size(105, 13);
            this.label20.TabIndex = 17;
            this.label20.Text = "Alliance -> Character";
            // 
            // StandingsForm
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(631, 118);
            this.Controls.Add(this.allianceAllianceValue);
            this.Controls.Add(this.label16);
            this.Controls.Add(this.allianceCorporationValue);
            this.Controls.Add(this.label18);
            this.Controls.Add(this.allianceCharacterValue);
            this.Controls.Add(this.label20);
            this.Controls.Add(this.corporationAllianceValue);
            this.Controls.Add(this.label14);
            this.Controls.Add(this.corporationCorporationValue);
            this.Controls.Add(this.label12);
            this.Controls.Add(this.corporationCharacterValue);
            this.Controls.Add(this.label10);
            this.Controls.Add(this.personalAllianceValue);
            this.Controls.Add(this.label7);
            this.Controls.Add(this.personalCorporationValue);
            this.Controls.Add(this.label5);
            this.Controls.Add(this.personalCharacterValue);
            this.Controls.Add(this.label3);
            this.Controls.Add(this.derivedValue);
            this.Controls.Add(this.label1);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedToolWindow;
            this.MaximizeBox = false;
            this.MinimizeBox = false;
            this.Name = "StandingsForm";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterParent;
            this.Text = "Standings";
            this.Load += new System.EventHandler(this.Standings_Load);
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.Label derivedValue;
        private System.Windows.Forms.Label label3;
        private System.Windows.Forms.Label personalCharacterValue;
        private System.Windows.Forms.Label label5;
        private System.Windows.Forms.Label personalCorporationValue;
        private System.Windows.Forms.Label label7;
        private System.Windows.Forms.Label personalAllianceValue;
        private System.Windows.Forms.Label corporationCharacterValue;
        private System.Windows.Forms.Label label10;
        private System.Windows.Forms.Label corporationCorporationValue;
        private System.Windows.Forms.Label label12;
        private System.Windows.Forms.Label corporationAllianceValue;
        private System.Windows.Forms.Label label14;
        private System.Windows.Forms.Label allianceAllianceValue;
        private System.Windows.Forms.Label label16;
        private System.Windows.Forms.Label allianceCorporationValue;
        private System.Windows.Forms.Label label18;
        private System.Windows.Forms.Label allianceCharacterValue;
        private System.Windows.Forms.Label label20;
    }
}